name: eit
description: "agent app"

publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.4
  geolocator: ^9.0.2
  get: ^4.6.6
  google_maps_flutter: ^2.5.3
  http: ^0.13.6
  intl: ^0.19.0
  location: ^5.0.0
  logger: ^2.0.2+1
  open_file: ^3.3.2
  package_info_plus: ^7.0.0
  path_provider: ^2.1.2
  pdf: ^3.6.0
  permission_handler: ^10.2.0
  place_picker: ^0.10.0
  printing: ^5.11.1
  shared_preferences: ^2.2.2
  simple_barcode_scanner: ^0.0.8
  syncfusion_flutter_datagrid: ^25.1.35
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 800
